/**
 * This class holds a number of constants to be used
 * with respect to application configuration.
 *
 * @author Josh Russell (Riptide Software, Inc.)
 * @auther Alex Acosta  (Riptide Software, Inc.)
 */
public class McLabsConstants {
    
    public static final String CONTENT_TYPE_XML = 'application/soap+xml';
    public static final String CONFIGURATION_NAME = 'RCM1OrgWideConfig';
    
    public static final String RCM1_API_URL = 'https://api.rcm1.com';
    public static final String RCM1_API_TEST_URL = 'https://testapi.rcm1.com';
    
    // Rmc1 Namespaces
    public static final String RCM1_S_NAMESPACE = 'http://www.w3.org/2003/05/soap-envelope';
    public static final String RCM1_A_NAMESPACE = 'http://www.w3.org/2005/08/addressing';
    public static final String RCM1_B_NAMESPACE = 'http://schemas.datacontract.org/2004/07/RCM.DataExchange';
    public static final String RCM1_I_NAMESPACE = 'http://www.w3.org/2001/XMLSchema-instance';
    public static final String RCM1_XS_NAMESPACE = 'http://www.w3.org/2001/XMLSchema';
    public static final String RCM1_DIFFGR_NAMESPACE = 'urn:schemas-microsoft-com:xml-diffgram-v1';
    public static final String RCM1_ARRAY_NAMESPACE = 'http://schemas.microsoft.com/2003/10/Serialization/Arrays';
    
}